CREATE TABLE IF NOT EXISTS evento (
                                      id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    nombre VARCHAR(255),
    tipo VARCHAR(255),
    fecha VARCHAR(100),
    descripcion VARCHAR(255)
    );
CREATE TABLE IF NOT EXISTS preg_recluta (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni INT NOT NULL UNIQUE,
    nombre VARCHAR(100),
    edad INT,
    res1 INT, res2 INT, res3 INT, res4 INT,
    res5 INT, res6 INT, res7 INT, res8 INT,
    ubicacion VARCHAR(100),
    estado VARCHAR(50)
);