CREATE TABLE IF NOT EXISTS evento (
                                      id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    nombre VARCHAR(255),
    tipo VARCHAR(255),
    fecha VARCHAR(100),
    descripcion VARCHAR(255)
    );